name: spot_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.1
  country_code_picker: ^1.2.4
  dotted_border: ^1.0.4
  provider: ^4.0.1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
  fonts:
    - family: proxima
      fonts:
        - asset: assets/fonts/proxima_ssv/ProximaNova-Regular.otf
          weight: 400

    - family: qanelas
      fonts:
        - asset: assets/fonts/qanelas/Qanelas-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/qanelas/Qanelas-Thin.ttf
          weight: 200
        - asset: assets/fonts/qanelas/Qanelas-Light.ttf
          weight: 300
        - asset: assets/fonts/qanelas/Qanelas-Regular.ttf
          weight: 400
        - asset: assets/fonts/qanelas/Qanelas-Medium.ttf
          weight: 500
        - asset: assets/fonts/qanelas/Qanelas-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/qanelas/Qanelas-Heavy.ttf
          weight: 700
        - asset: assets/fonts/qanelas/Qanelas-Bold.ttf
          weight: 800
        - asset: assets/fonts/qanelas/Qanelas-ExtraBold.ttf
          weight: 900

    - family: playFairItalic
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-BoldItalic.ttf
          weight: 800

