name: spot_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.1
  country_code_picker: ^1.2.4
  dotted_border: ^1.0.4
  provider: ^4.0.1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.1+1
  shared_preferences: ^0.5.6+1
  basic_utils: ^1.2.0
  qr_code_scanner: ^0.0.12
  cloudinary_client: ^0.0.9
  multi_image_picker: ^4.6.5
  path_provider: ^1.6.11
  place_picker: ^0.9.14
  skeleton_text: ^1.0.0
  url_launcher: ^5.5.0
  flutter_web_browser: "^0.11.0"
  uni_links: ^0.4.0
  webview_flutter: ^0.3.22+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
  fonts:
    - family: proxima
      fonts:
        - asset: assets/fonts/proxima_ssv/ProximaNova-Regular.otf
          weight: 400

    - family: qanelas
      fonts:
        - asset: assets/fonts/qanelas/Qanelas-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/qanelas/Qanelas-Thin.ttf
          weight: 200
        - asset: assets/fonts/qanelas/Qanelas-Light.ttf
          weight: 300
        - asset: assets/fonts/qanelas/Qanelas-Regular.ttf
          weight: 400
        - asset: assets/fonts/qanelas/Qanelas-Medium.ttf
          weight: 500
        - asset: assets/fonts/qanelas/Qanelas-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/qanelas/Qanelas-Heavy.ttf
          weight: 700
        - asset: assets/fonts/qanelas/Qanelas-Bold.ttf
          weight: 800
        - asset: assets/fonts/qanelas/Qanelas-ExtraBold.ttf
          weight: 900

    - family: playFairItalic
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-BoldItalic.ttf
          weight: 800

