name: spot_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/proxima_ssv/ProximaNova-Regular.otf
          weight: 400

    - family: Qanelas
      fonts:
        - asset: assets/fonts/qanelas/Qanelas-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/qanelas/Qanelas-Thin.ttf
          weight: 200
        - asset: assets/fonts/qanelas/Qanelas-Light.ttf
          weight: 300
        - asset: assets/fonts/qanelas/Qanelas-Regular.ttf
          weight: 400
        - asset: assets/fonts/qanelas/Qanelas-Medium.ttf
          weight: 500
        - asset: assets/fonts/qanelas/Qanelas-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/qanelas/Qanelas-Heavy.ttf
          weight: 700
        - asset: assets/fonts/qanelas/Qanelas-Bold.ttf
          weight: 800
        - asset: assets/fonts/qanelas/Qanelas-ExtraBold.ttf
          weight: 900

